"""add created_at to user

Revision ID: 37efa633b279
Revises: 
Create Date: 2026-05-17 20:41:34.465727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37efa633b279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("NOW()")
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
