"""make username unique

Revision ID: e3d312707b7d
Revises: 37efa633b279
Create Date: 2026-05-17 21:12:43.231906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d312707b7d'
down_revision = '37efa633b279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_users_username",
        "users",
        ["username"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_users_username",
        "users",
        type_="unique"
    )
    # ### end Alembic commands ###
